### PR TITLE
Add coverage check to pytest

### PR DESCRIPTION
**Pull request by mrchrisadams**
This PR adds coverage checking, to the testing setup, as described in  #14 .

You can read more about coverage here:

https://pytest-cov.readthedocs.io

This at least gives an idea if the key paths are covered.

### CODE REVIEW

**Comment by jonathan-s** [comment]
Might be a good idea to add https://codecov.io/ too. Then it'll be visible in the PR what the change in code coverage is.

**Comment by mrchrisadams** [comment]
Can you add the necessary config file if needed to this PR?

**Comment by jonathan-s** [comment]
There you go.

**Comment by jonathan-s** [comment]
Logging in to codecov.io allows you to browse the files as well and drill down to see codecoverage on each file.

**Comment by arendjantetteroo** [comment]
Cool stuff

**Comment by mrchrisadams** [comment]
I didn't know how to set this up, so thanks Jonathan 👍

**Pull request merged**
